# Generated by Django 3.2 on 2021-05-14 07:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crpractice', '0002_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('article', models.ManyToManyField(blank=True, related_name='hashtag', to='crpractice.Article')),
            ],
        ),
    ]
